---
title: "Visualização de Dados"
author: "Hugo Silva e Raquel Teixeira"
affiliation: 
    - Escola Nacional de Saúde Pública
date: today
date-format: long
lang: pt 
format:
  html:
    preview: false
    smooth-scroll: true
    embed-resources: true
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 3
    code_download: true
    code-copy: true
    output-file: data_Manipulation.html
    output-dir: output/documents
execute:
  warning: false
  collapse: true
  message: false
  eval: true
  echo: true
title-block-style: default
editor: 
  markdown: 
    wrap: 72
project:
  output-dir: output/documents
---
```{r, pacote e dados}
#| echo: false
#| include: false

rm(list = ls(all.names = TRUE)) # limpa todos os objetos, incluindo os ocultos

# Lista de pacotes
packages <- c(
  "janitor", "tidyverse", "rio", "here", "haven", 
  "data.table", "lubridate", "readxl", "broom", 
  "gt", "gtsummary"
)

# Instala pacotes que ainda não estão instalados
packages_to_install <- packages[!packages %in% installed.packages()[, "Package"]]
if (length(packages_to_install) > 0) {
  install.packages(packages_to_install)
}

# Carrega todos os pacotes
lapply(packages, library, character.only = TRUE)


inquerito_AVC_2024 <- read_excel("datasets/inquerito_AVC_2024_processed.xlsx") |> 
  clean_names()

names(inquerito_AVC_2024)

#ordenar sempre a altura do questionário

inquerito_AVC_2024$altura_questionario <- factor(inquerito_AVC_2024$altura_questionario, 
                                                              levels = c("Pré-Intervenção", "Pós-intervenção")) 

n_row_pre <- inquerito_AVC_2024 %>%
  filter(altura_questionario == "Pré-Intervenção") %>%
  nrow()

n_row_pos <- inquerito_AVC_2024 %>%
  filter(altura_questionario == "Pós-intervenção") %>%
  nrow()

summary_inquerito_by_ucc <- inquerito_AVC_2024 %>% 
  summarise(
    count = n(),
.by = c(altura_questionario, ucc), 
  ) %>%
  arrange(altura_questionario)

summary_inquerito_by_ucc

summary_inquerito_by_agrupamento <- inquerito_AVC_2024 %>% 
  summarise(
    count = n(),
.by = c(altura_questionario, agrupamento_escolas)
  ) %>%
  arrange(altura_questionario)

summary_inquerito_by_agrupamento


str(inquerito_AVC_2024$sexo)

# Recodificar a variável sexo
inquerito_AVC_2024 <- inquerito_AVC_2024 %>%
  mutate(
    sexo_alterado = factor(
      case_when(
        sexo == "Feminino" ~ 1,
        sexo == "Masculino" ~ 2,
        sexo == "Sem resposta" ~ NA_real_
      ),
      levels = c(1, 2),
      labels = c("Feminino", "Masculino")
    )
  )

str(inquerito_AVC_2024$sexo_alterado)
```


# Visualização de Dados

## Contagem de inquéritos respondidos por UCC pré e pós-intervenção

```{r}
summary_inquerito_by_ucc$altura_questionario <- factor(summary_inquerito_by_ucc$altura_questionario, 
                                                              levels = c("Pré-Intervenção", "Pós-intervenção")) 

summary_inquerito_by_ucc <- inquerito_AVC_2024 %>%
  filter(ucc %in% c("A", "B", "C", "D", "E")) %>%
  group_by(altura_questionario, ucc) %>%
  summarise(count = n(), .groups = "drop") %>%
  arrange(altura_questionario)


table_ucc <- ggplot(data = summary_inquerito_by_ucc, aes(x = altura_questionario, y = count, fill = ucc)
                  ) +
  geom_bar(stat = "identity", position = "dodge", width = 0.8) +
  labs(title = "Número de alunos por UCC e Altura do Questionário",
       x = "Altura do Questionário",
       y = "Número de Alunos",
       fill = "UCC") +
  scale_fill_manual(values = c("A" = "skyblue1",   # Azul Claro
                              "B" = "skyblue2",   # Azul Claro
                              "C" = "skyblue3",   # Azul Claro
                              "D" = "skyblue4",
                              "E" = "#607d8b")) +
  theme_minimal()

table_ucc
```

## Contagem de inquéritos respondidos por agrupamento pré e pós-intervenção

```{r}

grafico_alunos_por_agrupamento <- ggplot(data = summary_inquerito_by_agrupamento, 
                                         aes(x = agrupamento_escolas, 
                                             y = count, 
                                             fill = agrupamento_escolas)) +
  geom_bar(stat = "identity") +
  labs(title = "Número de alunos por agrupamento",
       x = "Agrupamentos de Escolas",
       y = "Alunos", 
       fill = "Legenda") +
  facet_wrap(~ altura_questionario) +
  scale_fill_manual(values = c("A1" = "skyblue1", 
                               "A2" = "skyblue1",
                               "B1" = "skyblue2", 
                               "B2" = "skyblue2",
                               "C1" = "skyblue3", 
                               "C2" = "skyblue3", 
                               "C3" = "skyblue3",
                               "D1" = "skyblue4", 
                               "D2" = "skyblue4", 
                               "D3" = "skyblue4", 
                               "D4" = "skyblue4",
                               "E1" = "#607d8b", 
                               "E2" = "#607d8b", 
                               "E3" = "#607d8b")) +
  theme_minimal(base_size = 10) + 
  theme(plot.title = element_text(size = 20),  # Tamanho do título
        axis.title = element_text(size = 12),  # Tamanho dos títulos dos eixos
        axis.text.x = element_blank(),   # tira os valores do x
        strip.text = element_text(size = 14), # Tamanho do texto das facetas
        axis.title.x = element_text(margin = margin(t = 10)),  # Espaço acima do título do eixo X
        axis.title.y = element_text(margin = margin(r = 10)),  # Espaço à direita do título do eixo Y
        legend.title.align = 1.2,
        anel.grid.minor = element_blank(),
        panel.grid.major = element_blank()
  )
  
grafico_alunos_por_agrupamento  

```

## Distribuição dos inquéritos respondidos por sexo pré e pós-intervenção

```{r}
inquerito_AVC_2024$altura_questionario <- factor(inquerito_AVC_2024$altura_questionario, 
                                                              levels = c("Pré-Intervenção", "Pós-intervenção")) 

inquerito_AVC_2024 <- inquerito_AVC_2024 %>%
  filter(!is.na(sexo_alterado))

distribuicao_sexo <- ggplot(inquerito_AVC_2024, aes(x = sexo_alterado, fill = sexo_alterado)) +
  geom_bar() +
  labs(title = "Distribuição por Sexo",
       x = "Sexo",
       y = "Contagem") +
  scale_fill_manual(values = c("Masculino" = "#4287f5", "Feminino" = "#f542a7")) +
  facet_wrap(~ altura_questionario) +
  theme_minimal()

distribuicao_sexo

```
